const REGION_URL='https://raw.githubusercontent.com/openpolis/geojson-italy/master/geojson/limits_IT_regions.geojson';
const MUNICIPALITIES_URL=code=>`https://raw.githubusercontent.com/openpolis/geojson-italy/master/topojson/limits_R_${String(code).padStart(2,'0')}_municipalities.topo.json`;
const categories=['Producer','Artista','Fonico','Studio','Videomaker','DJ'];
const genres=['Pop','Hip-Hop / Rap','R&B / Soul','Reggaeton','Latin Pop','Latin Trap','Latin Urban','Afrobeats','Amapiano','Brazilian Funk / Funk Carioca','K-Pop','EDM / Electronic','House','Tech House','Afro House','Dance / Eurodance','Drill','Trap','Rage / Opium-style Rap','Alternative / Indie','Indie Pop','Rock / Alternative Rock','Country','Country Pop','Singer-Songwriter / Acoustic','Folk','J-Pop','Dancehall','Jersey Club','Hyperpop / Digicore'];
const profiles=[{name:'@pashabeats',type:'Producer',genres:['Hip-Hop / Rap','Trap','R&B / Soul'],city:'Firenze',lat:43.7696,lng:11.2558},{name:'@nightroom',type:'Studio',genres:['R&B / Soul','Pop'],city:'Milano',lat:45.4642,lng:9.19},{name:'@romasound',type:'Fonico',genres:['Hip-Hop / Rap','Trap'],city:'Roma',lat:41.9028,lng:12.4964},{name:'@vesuviobeats',type:'Producer',genres:['Afro House','Hip-Hop / Rap'],city:'Napoli',lat:40.8518,lng:14.2681},{name:'@palermovibe',type:'Artista',genres:['Pop','Indie Pop'],city:'Palermo',lat:38.1157,lng:13.3615}];
const regionOrder=['Abruzzo','Basilicata','Calabria','Campania','Emilia-Romagna','Friuli-Venezia Giulia','Lazio','Liguria','Lombardia','Marche','Molise','Piemonte','Puglia','Sardegna','Sicilia','Toscana','Trentino-Alto Adige','Umbria','Valle d’Aosta','Veneto'];
const regionCodes={'Piemonte':1,'Valle d’Aosta':2,'Lombardia':3,'Trentino-Alto Adige':4,'Veneto':5,'Friuli-Venezia Giulia':6,'Liguria':7,'Emilia-Romagna':8,'Toscana':9,'Umbria':10,'Marche':11,'Lazio':12,'Abruzzo':13,'Molise':14,'Campania':15,'Puglia':16,'Basilicata':17,'Calabria':18,'Sicilia':19,'Sardegna':20};
const regionForCity={Firenze:'Toscana',Milano:'Lombardia',Roma:'Lazio',Napoli:'Campania',Palermo:'Sicilia',Bologna:'Emilia-Romagna',Torino:'Piemonte',Bari:'Puglia',Venezia:'Veneto',Genova:'Liguria',Cagliari:'Sardegna'};
const events=[{id:1,title:'Producer Night Firenze',region:'Toscana',city:'Firenze',date:'20 SET · 21:00',desc:'Beat, ascolti e networking tra producer e artisti toscani.'},{id:2,title:'Rap Meetup Milano',region:'Lombardia',city:'Milano',date:'27 SET · 20:30',desc:'Serata aperta a rapper, producer, DJ e videomaker.'},{id:3,title:'Studio Session Roma',region:'Lazio',city:'Roma',date:'04 OTT · 18:00',desc:'Incontro tra artisti indipendenti e professionisti locali.'},{id:4,title:'Afro Night Napoli',region:'Campania',city:'Napoli',date:'11 OTT · 22:00',desc:'Producer e artisti si incontrano per una sessione collettiva.'},{id:5,title:'Sicilia Urban Meetup',region:'Sicilia',city:'Palermo',date:'18 OTT · 19:30',desc:'Raduno della scena urban siciliana.'}];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],norm=s=>String(s||'').toUpperCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/’/g,"'").trim();
let map=null,regionLayer=null,italyBounds=null,selectedLayer=null,selectedRegion='',cityCache={};const cats=new Set(),gens=new Set();
function buildFilters(){
 $('#categories').innerHTML=categories.map(x=>`<button class="chip" data-group="cat" data-value="${x}">${x}</button>`).join('');
 $('#genres').innerHTML=genres.slice(0,6).map(x=>`<button class="chip" data-group="genre" data-value="${x}">${x}</button>`).join('')+`<button class="chip more-chip">Altro</button>`;
 $('#profileCats').innerHTML=categories.map(x=>`<button class="chip" data-profile="cat" data-value="${x}">${x}</button>`).join('');
 $('#profileGenres').innerHTML=genres.slice(0,6).map(x=>`<button class="chip" data-profile="genre" data-value="${x}">${x}</button>`).join('')+`<button class="chip more-profile">Altro</button>`;
 document.addEventListener('click',e=>{let b=e.target.closest('.more-chip,.more-profile');if(b){const profile=b.classList.contains('more-profile'),box=profile?$('#profileGenres'):$('#genres');box.innerHTML=genres.map(x=>`<button class="chip" data-${profile?'profile':'group'}="genre" data-value="${x}">${x}</button>`).join('');return}b=e.target.closest('.chip');if(!b)return;if(b.dataset.profile)toggleProfile(b);else if(b.dataset.group)toggleFilter(b)});
}
function toggleFilter(b){const set=b.dataset.group==='cat'?cats:gens,v=b.dataset.value;set.has(v)?set.delete(v):set.add(v);b.classList.toggle('active',set.has(v));renderProfiles()}
function toggleProfile(b){const group=b.dataset.profile,all=$$(`[data-profile="${group}"]`),sel=all.filter(x=>x.classList.contains('selected')).length;if(!b.classList.contains('selected')&&sel>=3)return;b.classList.toggle('selected')}
function renderProfiles(){const q=($('#search').value||'').toLowerCase().trim();const list=profiles.filter(p=>(!q||[p.name,p.city,p.type,...p.genres].join(' ').toLowerCase().includes(q))&&(!cats.size||cats.has(p.type))&&(!gens.size||p.genres.some(g=>gens.has(g))));$('#count').textContent=list.length;$('#profiles').innerHTML=list.length?list.map(p=>{const u=p.name.slice(1);return `<article class="profile"><div class="who"><div class="avatar"><img src="https://unavatar.io/instagram/${encodeURIComponent(u)}" alt="" loading="lazy" onerror="this.style.display='none'"><span>${u[0].toUpperCase()}</span></div><div><b>${p.name}</b><small>${p.type} · ${p.genres.slice(0,3).join(' · ')} · ${p.city}</small></div></div><button class="igbtn" data-ig="${u}">Instagram</button></article>`}).join(''):`<div class="profile"><div><b>Nessun risultato</b><small>Prova un altro filtro.</small></div></div>`;$$('[data-ig]').forEach(b=>b.onclick=()=>window.open('https://instagram.com/'+b.dataset.ig,'_blank','noopener'))}
function regionName(f){return f?.properties?.reg_name||f?.properties?.NOME_REG||f?.properties?.name||''}function regionCode(f){return Number(f?.properties?.reg_istat_code_num||f?.properties?.reg_istat_code||0)||null}function styleRegion(){return{className:'region',weight:1.1,color:'#302c37',fillColor:'#0e0e14',fillOpacity:.96}}function markerIcon(){return L.divIcon({className:'sonap',iconSize:[9,9],iconAnchor:[4.5,4.5]})}
function buildRegionList(){ $('#regionList').innerHTML=`<div class="region-list-title">REGIONI</div>`+regionOrder.map(r=>`<button class="region-item" data-region="${r}">${r}<span>›</span></button>`).join('');$$('.region-item').forEach(b=>b.onclick=()=>selectRegion(b.dataset.region))}
function selectRegion(name,layer=null){selectedRegion=name;selectedLayer=layer||regionLayer?.getLayers().find(x=>norm(regionName(x.feature))===norm(name))||null;if(selectedLayer){regionLayer.eachLayer(x=>x.setStyle(styleRegion(x.feature)));selectedLayer.setStyle({fillColor:'#1b1421',color:'#ff27c7',weight:1.7});map.fitBounds(selectedLayer.getBounds(),{padding:[30,30],maxZoom:7.7,duration:.65})}$('#mapTitle').textContent=name;$('#mapSub').textContent='Città della regione';$('#reset').classList.add('show');$$('.region-item').forEach(b=>b.classList.toggle('active',norm(b.dataset.region)===norm(name)));$('#citiesTitle').textContent=name;$('#citiesPanel').classList.remove('hidden');loadCities(name)}
async function loadCities(name){const box=$('#citiesList');if(cityCache[name])return showCities(cityCache[name]);box.innerHTML='<span class="city-pill">Caricamento…</span>';try{const r=await fetch(MUNICIPALITIES_URL(regionCodes[name]),{cache:'force-cache'});if(!r.ok)throw Error();const topo=await r.json(),obj=topojson.feature(topo,topo.objects[Object.keys(topo.objects)[0]]);const names=[...new Set(obj.features.map(f=>f.properties?.name||f.properties?.COMUNE||f.properties?.NAME_2).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'it'));cityCache[name]=names;showCities(names)}catch(e){box.innerHTML='<span class="city-pill">Città non disponibili</span>'}}
function showCities(names){$('#citiesCount').textContent=names.length+' città';const q=($('#citySearch').value||'').toLowerCase();$('#citiesList').innerHTML=names.filter(n=>n.toLowerCase().includes(q)).map(n=>`<button class="city-pill" data-city="${n}">${n}</button>`).join('');$$('[data-city]').forEach(b=>b.onclick=()=>{$('#search').value=b.dataset.city;renderProfiles();window.scrollTo({top:0,behavior:'smooth'})})}
function resetMap(){selectedRegion='';selectedLayer=null;regionLayer?.eachLayer(x=>x.setStyle(styleRegion(x.feature)));map.flyTo([41.9,12.5],5.15,{duration:.65});$('#mapTitle').textContent='Tutta Italia';$('#mapSub').textContent='Tocca una regione per entrare';$('#reset').classList.remove('show');$$('.region-item').forEach(b=>b.classList.remove('active'));$('#citiesPanel').classList.add('hidden')}
async function initMap(){if(map)return;italyBounds=L.latLngBounds([[35.25,5.8],[47.7,19.2]]);map=L.map('map',{zoomControl:false,attributionControl:false,minZoom:5.15,maxZoom:12,maxBounds:italyBounds,maxBoundsViscosity:1,worldCopyJump:false,preferCanvas:true,zoomAnimation:true,fadeAnimation:false,markerZoomAnimation:false}).setView([41.9,12.5],5.15);profiles.forEach(p=>L.marker([p.lat,p.lng],{icon:markerIcon(),keyboard:false}).addTo(map).bindTooltip(`<b>${p.name}</b><br>${p.type} · ${p.city}`,{className:'sona-tip',direction:'top',offset:[0,-7]}));const r=await fetch(REGION_URL,{cache:'force-cache'});if(!r.ok)throw Error();const data=await r.json();regionLayer=L.geoJSON(data,{style:styleRegion,onEachFeature:(f,l)=>l.on({click:()=>selectRegion(regionName(f),l),mouseover:e=>e.target.setStyle({fillColor:'#17131d',color:'#7657ff'}),mouseout:e=>{if(e.target!==selectedLayer)e.target.setStyle(styleRegion(f))}})}).addTo(map);map.setMaxBounds(italyBounds)}
function renderEvents(){const saved=JSON.parse(localStorage.getItem('sonaProfile')||'null'),near=regionForCity[saved?.city||'Firenze']||'Toscana',mode=$$('.event-filter.active')[0]?.dataset.region||near,q=($('#eventSearch').value||'').toLowerCase();const list=events.filter(e=>(mode==='Italia'||e.region===mode)&&(!q||`${e.title} ${e.city} ${e.region}`.toLowerCase().includes(q)));$('#eventsLocation').textContent=mode==='Italia'?'Italia':mode;const ids=JSON.parse(localStorage.getItem('sonaRsvp')||'[]');$('#eventsList').innerHTML=list.length?list.map(e=>`<article class="event-card"><div class="event-date">${e.date} · ${e.city.toUpperCase()}</div><h3>${e.title}</h3><p>${e.desc}</p><div class="event-foot"><small>${e.region}</small><button class="rsvp ${ids.includes(e.id)?'done':''}" data-rsvp="${e.id}">${ids.includes(e.id)?'PARTECIPERAI':'CONFERMA PARTECIPAZIONE'}</button></div></article>`).join(''):'<div class="profile"><b>Nessun evento trovato.</b><small>Prova tutta Italia o un’altra ricerca.</small></div>';$$('[data-rsvp]').forEach(b=>b.onclick=()=>{let a=JSON.parse(localStorage.getItem('sonaRsvp')||'[]'),id=Number(b.dataset.rsvp);a=a.includes(id)?a.filter(x=>x!==id):[...a,id];localStorage.setItem('sonaRsvp',JSON.stringify(a));renderEvents()})}
function openEvents(){const near=regionForCity[JSON.parse(localStorage.getItem('sonaProfile')||'null')?.city||'Firenze']||'Toscana';$$('.event-filter').forEach(x=>x.classList.toggle('active',x.dataset.region==='Toscana'));$('#eventsPanel').classList.add('open');renderEvents()}function closeEvents(){$('#eventsPanel').classList.remove('open')}
function openSheet(){const s=JSON.parse(localStorage.getItem('sonaProfile')||'null');if(s){$('#ig').value=s.ig||'';$('#city').value=s.city||'';$$('[data-profile]').forEach(b=>b.classList.toggle('selected',(b.dataset.profile==='cat'?s.categories||[]:s.genres||[]).includes(b.dataset.value)))}$('#sheet').classList.remove('hidden')}
function saveProfile(){const cats=$$('[data-profile="cat"].selected').map(x=>x.dataset.value),gs=$$('[data-profile="genre"].selected').map(x=>x.dataset.value);localStorage.setItem('sonaProfile',JSON.stringify({ig:$('#ig').value.trim()||'@pashabeats',city:$('#city').value.trim()||'Firenze',categories:cats,genres:gs}));$('#sheet').classList.add('hidden')}
function wire(){buildFilters();buildRegionList();renderProfiles();$('#search').oninput=renderProfiles;$('#citySearch').oninput=()=>selectedRegion&&showCities(cityCache[selectedRegion]||[]);$('#reset').onclick=resetMap;$('#profileOpen').onclick=openSheet;$('#joinOpen').onclick=openSheet;$('#closeSheet').onclick=()=>$('#sheet').classList.add('hidden');$('#save').onclick=saveProfile;$('#connectInstagram').onclick=()=>$('#connectNote').textContent='Collegamento pronto per l’autenticazione ufficiale Instagram/Meta.';$('#citiesBack').onclick=()=>{$('#citiesPanel').classList.add('hidden');resetMap()};$('#eventsClose').onclick=closeEvents;$$('.event-filter').forEach(b=>b.onclick=()=>{$$('.event-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderEvents()});$('#eventSearch').oninput=renderEvents;let sx=0,sy=0;document.addEventListener('touchstart',e=>{sx=e.changedTouches[0].clientX;sy=e.changedTouches[0].clientY},{passive:true});document.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx,dy=e.changedTouches[0].clientY-sy;if(dx>90&&Math.abs(dx)>Math.abs(dy)*1.25)openEvents()},{passive:true})}
wire();const boot=()=>initMap().catch(()=>$('#mapTitle').textContent='Mappa non disponibile');if('requestIdleCallback'in window)requestIdleCallback(boot,{timeout:900});else setTimeout(boot,200);