const REGION_URL='https://raw.githubusercontent.com/openpolis/geojson-italy/master/geojson/limits_IT_regions.geojson';
const categories=['Producer','Artista','Fonico','Studio','Videomaker','DJ'];
const genres=['Hip-Hop','Trap','Pop','R&B','House','Techno','Afro House','Indie','Rock','EDM'];
const profiles=[{id:1,name:'@pashabeats',type:'Producer',genres:['Hip-Hop','Trap','R&B'],city:'Firenze',lat:43.7696,lng:11.2558},{id:2,name:'@nightroom',type:'Studio',genres:['R&B','Pop'],city:'Milano',lat:45.4642,lng:9.19},{id:3,name:'@romasound',type:'Fonico',genres:['Hip-Hop','Trap'],city:'Roma',lat:41.9028,lng:12.4964},{id:4,name:'@vesuviobeats',type:'Producer',genres:['Afro House','Hip-Hop'],city:'Napoli',lat:40.8518,lng:14.2681},{id:5,name:'@palermovibe',type:'Artista',genres:['Pop','Indie'],city:'Palermo',lat:38.1157,lng:13.3615}];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const map=L.map('map',{zoomControl:false,attributionControl:false,zoomSnap:.25,minZoom:4,maxZoom:12,preferCanvas:true,zoomAnimation:true,fadeAnimation:false,markerZoomAnimation:false}).setView([41.9,12.5],5.15);let regionLayer=null,selectedRegion=null,locationCircle=null,locationMarker=null;const categoryState=new Set(),genreState=new Set();
const regionCentroids={'PIEMONTE':[45.05,7.65],'VALLE D\'AOSTA':[45.74,7.31],'LOMBARDIA':[45.5,9.9],'TRENTINO-ALTO ADIGE':[46.1,11.25],'VENETO':[45.55,11.85],'FRIULI-VENEZIA GIULIA':[46.1,13.15],'LIGURIA':[44.25,8.95],'EMILIA-ROMAGNA':[44.55,11.1],'TOSCANA':[43.4,11.0],'UMBRIA':[43.05,12.45],'MARCHE':[43.3,13.0],'LAZIO':[41.85,12.9],'ABRUZZO':[42.25,13.8],'MOLISE':[41.7,14.5],'CAMPANIA':[40.9,14.9],'PUGLIA':[41.0,16.0],'BASILICATA':[40.45,16.0],'CALABRIA':[39.05,16.3],'SICILIA':[37.6,14.1],'SARDEGNA':[40.0,9.0]};
function norm(s){return String(s||'').toUpperCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/’/g,"'")}function regionName(f){return f?.properties?.reg_name||f?.properties?.NOME_REG||f?.properties?.name||'Regione'}
function buildChips(){$('#categories').innerHTML=categories.map(x=>`<button class="chip" data-group="cat" data-value="${x}">${x}</button>`).join('');$('#genres').innerHTML=genres.map(x=>`<button class="chip" data-group="genre" data-value="${x}">${x}</button>`).join('');$('#profileCats').innerHTML=categories.map(x=>`<button class="chip" data-profile="cat" data-value="${x}">${x}</button>`).join('');$('#profileGenres').innerHTML=genres.map(x=>`<button class="chip" data-profile="genre" data-value="${x}">${x}</button>`).join('');document.addEventListener('click',e=>{const b=e.target.closest('.chip');if(!b)return;b.dataset.profile?toggleProfileChip(b):toggleFilterChip(b)})}
function toggleFilterChip(b){const set=b.dataset.group==='cat'?categoryState:genreState,v=b.dataset.value;set.has(v)?set.delete(v):set.add(v);b.classList.toggle('active',set.has(v));renderProfiles()}
function toggleProfileChip(b){const all=$$(`[data-profile="${b.dataset.profile}"]`),selected=all.filter(x=>x.classList.contains('selected')).length;if(!b.classList.contains('selected')&&selected>=3){b.animate([{transform:'translateX(0)'},{transform:'translateX(-3px)'},{transform:'translateX(3px)'},{transform:'translateX(0)'}],{duration:160});return}b.classList.toggle('selected')}
function renderProfiles(){const q=($('#search').value||'').trim().toLowerCase();const visible=profiles.filter(p=>{const text=[p.name,p.type,p.city,...p.genres].join(' ').toLowerCase();return(!q||text.includes(q))&&(!categoryState.size||categoryState.has(p.type))&&(!genreState.size||p.genres.some(g=>genreState.has(g)))});$('#count').textContent=visible.length;$('#profiles').innerHTML=visible.length?visible.map(p=>`<article class="profile"><div class="who"><div class="avatar">${p.name.replace('@','').slice(0,1).toUpperCase()}</div><div><b>${p.name}</b><small>${p.type} · ${p.genres.slice(0,3).join(' · ')} · ${p.city}</small></div></div><button class="igbtn" data-ig="${p.name}">Instagram</button></article>`).join(''):`<div class="profile"><div><b>Nessun risultato</b><small>Prova a cambiare filtri o zona.</small></div></div>`;$$('#profiles [data-ig]').forEach(b=>b.onclick=()=>window.open('https://instagram.com/'+b.dataset.ig.replace('@',''),'_blank','noopener'))}
function markerIcon(){return L.divIcon({className:'sonap',iconSize:[9,9],iconAnchor:[4.5,4.5]})}function addMarkers(){profiles.forEach(p=>L.marker([p.lat,p.lng],{icon:markerIcon(),keyboard:false}).addTo(map).bindTooltip(`<b>${p.name}</b><br>${p.type} · ${p.city}`,{className:'sona-tip',direction:'top',offset:[0,-7]}))}
function styleRegion(){return{className:'region',weight:1.1,color:'#302c37',fillColor:'#0e0e14',fillOpacity:.96}}function onRegion(f,l){const name=regionName(f);l.on({click:()=>zoomRegion(l,name),mouseover:e=>e.target.setStyle({fillColor:'#17131d',color:'#7657ff'}),mouseout:e=>{if(e.target!==selectedRegion)e.target.setStyle(styleRegion(f))}});const c=regionCentroids[norm(name)];if(c)L.marker(c,{interactive:false,icon:L.divIcon({className:'region-label',html:name.replace('TRENTINO-ALTO ADIGE','TRENTINO').replace('FRIULI-VENEZIA GIULIA','FRIULI').replace('EMILIA-ROMAGNA','EMILIA'),iconSize:[80,16],iconAnchor:[40,8]})}).addTo(map)}
function zoomRegion(l,name){selectedRegion=l;regionLayer.eachLayer(x=>x.setStyle(styleRegion(x.feature)));l.setStyle({fillColor:'#1b1421',color:'#ff27c7',weight:1.7});map.fitBounds(l.getBounds(),{padding:[30,30],maxZoom:7.4,duration:.7});$('#mapTitle').textContent=name;$('#mapSub').textContent='Tocca “Italia” per tornare indietro';$('#reset').classList.add('show')}function resetMap(){selectedRegion=null;regionLayer?.eachLayer(l=>l.setStyle(styleRegion(l.feature)));map.flyTo([41.9,12.5],5.15,{duration:.65});$('#mapTitle').textContent='Tutta Italia';$('#mapSub').textContent='Tocca una regione per entrare';$('#reset').classList.remove('show')}
async function loadRegions(){try{const r=await fetch(REGION_URL,{cache:'force-cache'});if(!r.ok)throw Error();const data=await r.json();regionLayer=L.geoJSON(data,{style:styleRegion,onEachFeature:onRegion,smoothFactor:1.5}).addTo(map)}catch(e){$('#mapTitle').textContent='Mappa offline';$('#mapSub').textContent='Ricarica per visualizzare i confini regionali'}}
function locateUser(){if(!navigator.geolocation){alert('La posizione non è disponibile su questo browser.');return}navigator.geolocation.getCurrentPosition(pos=>{const ll=[pos.coords.latitude,pos.coords.longitude];locationMarker?.remove();locationCircle?.remove();locationMarker=L.marker(ll,{icon:markerIcon()}).addTo(map).bindTooltip('La tua zona',{className:'sona-tip'}).openTooltip();locationCircle=L.circle(ll,{radius:5000,color:'#ff27c7',weight:1,opacity:.45,fillColor:'#ff27c7',fillOpacity:.035}).addTo(map);map.flyTo(ll,11,{duration:.8});$('#mapTitle').textContent='La tua zona';$('#mapSub').textContent='Raggio massimo 5 km'},()=>alert('Posizione non concessa. Puoi comunque cercare una città.'))}
function openSheet(){const saved=JSON.parse(localStorage.getItem('sonaProfile')||'null');if(saved){$('#ig').value=saved.ig||'';$('#city').value=saved.city||'';$$('[data-profile]').forEach(b=>b.classList.toggle('selected',(b.dataset.profile==='cat'?saved.categories:saved.genres)?.includes(b.dataset.value)))}$('#sheet').classList.remove('hidden')}function closeSheet(){$('#sheet').classList.add('hidden')}
function saveProfile(){const cats=$$('[data-profile="cat"].selected').map(x=>x.dataset.value),gs=$$('[data-profile="genre"].selected').map(x=>x.dataset.value);const ig=$('#ig').value.trim()||'@pashabeats',city=$('#city').value.trim()||'Firenze';localStorage.setItem('sonaProfile',JSON.stringify({ig,city,categories:cats,genres:gs}));closeSheet();alert('Profilo salvato su questo dispositivo.')}
buildChips();renderProfiles();addMarkers();loadRegions();$('#search').addEventListener('input',renderProfiles);$('#reset').onclick=resetMap;$('#locate').onclick=locateUser;$('#profileOpen').onclick=openSheet;$('#joinOpen').onclick=openSheet;$('#closeSheet').onclick=closeSheet;$('#save').onclick=saveProfile;$('#sheet').addEventListener('click',e=>{if(e.target===e.currentTarget)closeSheet()});