const REGION_URL='https://raw.githubusercontent.com/openpolis/geojson-italy/master/geojson/limits_IT_regions.geojson';
const MUNICIPALITIES_URL=c=>`https://raw.githubusercontent.com/openpolis/geojson-italy/master/topojson/limits_R_${String(c).padStart(2,'0')}_municipalities.topo.json`;
const CATEGORIES=['Producer','Artista','Fonico','Studio','Videomaker','DJ'];
const GENRES=['Pop','Hip-Hop / Rap','R&B / Soul','Reggaeton','Latin Pop','Latin Trap','Latin Urban','Afrobeats','Amapiano','Brazilian Funk / Funk Carioca','K-Pop','EDM / Electronic','House','Tech House','Afro House','Dance / Eurodance','Drill','Trap','Rage / Opium-style Rap','Alternative / Indie','Indie Pop','Rock / Alternative Rock','Country','Country Pop','Singer-Songwriter / Acoustic','Folk','J-Pop','Dancehall','Jersey Club','Hyperpop / Digicore'];
const REGIONS=['Abruzzo','Basilicata','Calabria','Campania','Emilia-Romagna','Friuli-Venezia Giulia','Lazio','Liguria','Lombardia','Marche','Molise','Piemonte','Puglia','Sardegna','Sicilia','Toscana','Trentino-Alto Adige','Umbria','Valle d’Aosta','Veneto'];
const CODES={Piemonte:1,'Valle d’Aosta':2,Lombardia:3,'Trentino-Alto Adige':4,Veneto:5,'Friuli-Venezia Giulia':6,Liguria:7,'Emilia-Romagna':8,Toscana:9,Umbria:10,Marche:11,Lazio:12,Abruzzo:13,Molise:14,Campania:15,Puglia:16,Basilicata:17,Calabria:18,Sicilia:19,Sardegna:20};
const MAJOR={Toscana:['Firenze','Prato','Livorno','Pisa','Arezzo','Siena','Lucca'],Lombardia:['Milano','Brescia','Bergamo','Monza','Como','Varese','Pavia'],Lazio:['Roma','Latina','Frosinone','Viterbo','Rieti'],Campania:['Napoli','Salerno','Caserta','Avellino','Benevento'],Piemonte:['Torino','Novara','Alessandria','Asti','Cuneo','Vercelli','Biella'],Veneto:['Venezia','Verona','Padova','Vicenza','Treviso','Rovigo','Belluno'],'Emilia-Romagna':['Bologna','Parma','Modena','Reggio Emilia','Ravenna','Rimini','Ferrara'],Puglia:['Bari','Lecce','Foggia','Taranto','Brindisi','Andria','Barletta'],Sicilia:['Palermo','Catania','Messina','Siracusa','Trapani','Ragusa','Agrigento'],Sardegna:['Cagliari','Sassari','Olbia','Alghero','Nuoro','Oristano','Carbonia'],Liguria:['Genova','La Spezia','Savona','Imperia'],Calabria:['Reggio Calabria','Catanzaro','Cosenza','Crotone','Vibo Valentia'],Abruzzo:['L’Aquila','Pescara','Chieti','Teramo'],Friuli:['Trieste','Udine','Pordenone','Gorizia'],Marche:['Ancona','Pesaro','Macerata','Ascoli Piceno','Fermo'],Umbria:['Perugia','Terni'],Trentino:['Trento','Bolzano'],Basilicata:['Potenza','Matera'],Molise:['Campobasso','Isernia'],Valle:['Aosta']};
const PROFILES=[{name:'@pashabeats',type:'Producer',genres:['Hip-Hop / Rap','Trap','R&B / Soul'],city:'Firenze',lat:43.7696,lng:11.2558},{name:'@nightroom',type:'Studio',genres:['R&B / Soul','Pop'],city:'Milano',lat:45.4642,lng:9.19},{name:'@romasound',type:'Fonico',genres:['Hip-Hop / Rap','Trap'],city:'Roma',lat:41.9028,lng:12.4964},{name:'@vesuviobeats',type:'Producer',genres:['Afro House','Hip-Hop / Rap'],city:'Napoli',lat:40.8518,lng:14.2681},{name:'@palermovibe',type:'Artista',genres:['Pop','Indie Pop'],city:'Palermo',lat:38.1157,lng:13.3615}];
const EVENTS=[{id:1,title:'Producer Night Firenze',region:'Toscana',city:'Firenze',date:'20 SET · 21:00',desc:'Beat, ascolti e networking tra producer e artisti toscani.'},{id:2,title:'Rap Meetup Milano',region:'Lombardia',city:'Milano',date:'27 SET · 20:30',desc:'Serata aperta a rapper, producer, DJ e videomaker.'},{id:3,title:'Studio Session Roma',region:'Lazio',city:'Roma',date:'04 OTT · 18:00',desc:'Incontro tra artisti indipendenti e professionisti locali.'},{id:4,title:'Afro Night Napoli',region:'Campania',city:'Napoli',date:'11 OTT · 22:00',desc:'Producer e artisti si incontrano per una sessione collettiva.'},{id:5,title:'Sicilia Urban Meetup',region:'Sicilia',city:'Palermo',date:'18 OTT · 19:30',desc:'Raduno della scena urban siciliana.'}];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/’/g,"'").toLowerCase().trim();
let map,regionLayer,selectedRegion='',selectedLayer=null,cityCache={},municipalityLayer=null,topoReady=false,globalCityCache=null,searchTimer=null;const selectedCats=new Set(),selectedGenres=new Set();
const cityIndex=Object.entries(MAJOR).flatMap(([region,cities])=>cities.map(city=>({city,region})));
function chips(){
 $('#categories').innerHTML=CATEGORIES.map(x=>`<button class="chip" data-filter="cat" data-value="${x}">${x}</button>`).join('');
 $('#genres').innerHTML=GENRES.slice(0,6).map(x=>`<button class="chip" data-filter="genre" data-value="${x}">${x}</button>`).join('')+`<button class="chip more" id="moreGenres">Altro</button>`;
 $('#profileCats').innerHTML=CATEGORIES.map(x=>`<button class="chip" data-profile="cat" data-value="${x}">${x}</button>`).join('');
 $('#profileGenres').innerHTML=GENRES.slice(0,6).map(x=>`<button class="chip" data-profile="genre" data-value="${x}">${x}</button>`).join('')+`<button class="chip moreProfile" id="moreProfile">Altro</button>`;
 document.addEventListener('click',e=>{const b=e.target.closest('.chip');if(!b)return;if(b.id==='moreGenres'){b.parentElement.innerHTML=GENRES.map(x=>`<button class="chip" data-filter="genre" data-value="${x}">${x}</button>`).join('');return}if(b.id==='moreProfile'){b.parentElement.innerHTML=GENRES.map(x=>`<button class="chip" data-profile="genre" data-value="${x}">${x}</button>`).join('');return}if(b.dataset.filter){const set=b.dataset.filter==='cat'?selectedCats:selectedGenres,v=b.dataset.value;set.has(v)?set.delete(v):set.add(v);b.classList.toggle('active',set.has(v));renderProfiles()}if(b.dataset.profile){const group=b.dataset.profile,selected=$$(`[data-profile="${group}"].selected`).length;if(!b.classList.contains('selected')&&selected>=3)return;b.classList.toggle('selected')}});
}
function renderProfiles(){const q=norm($('#search').value);const list=PROFILES.filter(p=>(!q||norm([p.name,p.city,p.type,...p.genres].join(' ')).includes(q))&&(!selectedCats.size||selectedCats.has(p.type))&&(!selectedGenres.size||p.genres.some(g=>selectedGenres.has(g))));$('#count').textContent=list.length;$('#profiles').innerHTML=list.length?list.map(p=>{const u=p.name.slice(1);return `<article class="profile"><div class="who"><div class="avatar"><img src="https://unavatar.io/instagram/${encodeURIComponent(u)}" alt="" loading="lazy" onload="this.parentElement.classList.add('loaded')" onerror="this.remove()"><span>${u[0].toUpperCase()}</span></div><div><b>${p.name}</b><small>${p.type} · ${p.genres.join(' · ')} · ${p.city}</small></div></div><button class="ig" data-ig="${u}">Instagram</button></article>`}).join(''):'<div class="profile"><div><b>Nessun risultato</b><small>Prova un altro filtro.</small></div></div>';$$('[data-ig]').forEach(b=>b.onclick=()=>window.open(`https://instagram.com/${b.dataset.ig}`,'_blank','noopener,noreferrer'))}
function regionName(f){return f?.properties?.reg_name||f?.properties?.NOME_REG||f?.properties?.name||''}function regionStyle(){return{className:'region',color:'#403b48',weight:1.1,fillColor:'#111017',fillOpacity:.94}}
function buildRegions(){const box=$('#regionList');box.innerHTML=REGIONS.map(r=>`<button class="region-item" data-region="${r}">${r}<span>›</span></button>`).join('');$$('.region-item').forEach(b=>b.onclick=()=>selectRegion(b.dataset.region))}
function selectRegion(name,layer){selectedRegion=name;selectedLayer=layer||regionLayer?.getLayers().find(x=>norm(regionName(x.feature))===norm(name));regionLayer?.eachLayer(x=>x.setStyle(regionStyle()));if(selectedLayer){selectedLayer.setStyle({fillColor:'#1a1520',color:'#ff35d7',weight:1.6});map.fitBounds(selectedLayer.getBounds(),{padding:[28,28],maxZoom:8,duration:.55})}$('#mapStatus').textContent=name;$('#reset').classList.add('show');$$('.region-item').forEach(b=>b.classList.toggle('active',norm(b.dataset.region)===norm(name)));$('.map-layout')?.classList.add('region-open');$('#citiesTitle').textContent=name;$('#citiesPanel').classList.remove('hidden');loadCities(name)}
async function ensureTopo(){if(topoReady)return;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://unpkg.com/topojson-client@3.1.0/dist/topojson-client.min.js';s.onload=()=>{topoReady=true;resolve()};s.onerror=reject;document.head.appendChild(s)})}
function cityName(f){return f?.properties?.name||f?.properties?.COMUNE||f?.properties?.NAME_2||f?.properties?.comune||''}
async function loadCities(name){const box=$('#citiesList');if(cityCache[name])return showCities(cityCache[name]);box.innerHTML='<span class="city-item">Caricamento città…</span>';try{await ensureTopo();const r=await fetch(MUNICIPALITIES_URL(CODES[name]),{cache:'force-cache'});const topo=await r.json();const obj=topojson.feature(topo,topo.objects[Object.keys(topo.objects)[0]]);const all=obj.features.map(f=>cityName(f)).filter(Boolean);cityCache[name]={all,features:obj.features};showCities(cityCache[name]);drawMajorCities(name,obj.features)}catch(e){box.innerHTML='<span class="city-item">Città non disponibili.</span>'}}
function showCities(data){const q=norm($('#citySearch').value);const list=data.all.filter(c=>!q||norm(c).includes(q)).sort((a,b)=>a.localeCompare(b,'it'));$('#citiesCount').textContent=`${data.all.length} città`;$('#citiesList').innerHTML=list.map(c=>`<button class="city-item" data-city="${c}">${c}</button>`).join('');$$('[data-city]').forEach(b=>b.onclick=()=>{$('#search').value=b.dataset.city;renderProfiles()})}
function drawMajorCities(region,features){if(municipalityLayer)municipalityLayer.remove();const targets=MAJOR[region]||[];const wanted=features.filter(f=>targets.some(t=>norm(t)===norm(cityName(f)))).slice(0,7);municipalityLayer=L.geoJSON({type:'FeatureCollection',features:wanted},{style:{color:'#3b3542',weight:.8,fillColor:'#0b0b10',fillOpacity:0},interactive:false}).addTo(map)}
async function searchAllCities(q){if(globalCityCache)return globalCityCache.filter(x=>norm(x.city).includes(q));await ensureTopo();const jobs=Object.entries(CODES).map(async([region,code])=>{try{const r=await fetch(MUNICIPALITIES_URL(code),{cache:'force-cache'});const topo=await r.json();const obj=topojson.feature(topo,topo.objects[Object.keys(topo.objects)[0]]);return obj.features.map(f=>({city:cityName(f),region})).filter(x=>x.city)}catch{return[]}});globalCityCache=(await Promise.all(jobs)).flat();return globalCityCache.filter(x=>norm(x.city).includes(q))}
async function handleSearch(){const q=norm($('#search').value);renderProfiles();if(q.length<2)return;const exact=cityIndex.find(x=>norm(x.city)===q);const partial=exact||cityIndex.find(x=>norm(x.city).startsWith(q));const regionMatch=REGIONS.find(r=>norm(r).startsWith(q));if(regionMatch){selectRegion(regionMatch);return}if(partial){selectRegion(partial.region);$('#citySearch').value=partial.city;return}if(q.length>=3&&!selectedRegion){const found=await searchAllCities(q);if(found[0]){selectRegion(found[0].region);setTimeout(()=>{$('#citySearch').value=found[0].city;showCities(cityCache[found[0].region]||{all:[],features:[]})},500)}}}
function resetMap(){selectedRegion='';selectedLayer=null;municipalityLayer?.remove();municipalityLayer=null;regionLayer?.eachLayer(x=>x.setStyle(regionStyle()));map.flyTo([41.9,12.5],5.15,{duration:.5});$('#mapStatus').textContent='Tutta Italia';$('#reset').classList.remove('show');$$('.region-item').forEach(b=>b.classList.remove('active'));$('#citiesPanel').classList.add('hidden');$('.map-layout')?.classList.remove('region-open')}
async function initMap(){map=L.map('map',{zoomControl:false,attributionControl:false,minZoom:5.15,maxZoom:12,maxBounds:L.latLngBounds([[35.25,5.8],[47.7,19.2]]),maxBoundsViscosity:1,worldCopyJump:false,preferCanvas:true}).setView([41.9,12.5],5.15);PROFILES.forEach(p=>L.circleMarker([p.lat,p.lng],{radius:4,color:'#fff',weight:1,fillColor:'#ff2bd6',fillOpacity:1}).addTo(map).bindTooltip(`<b>${p.name}</b><br>${p.type} · ${p.city}`,{className:'sona-tip'}));const r=await fetch(REGION_URL,{cache:'force-cache'});const data=await r.json();regionLayer=L.geoJSON(data,{style:regionStyle,onEachFeature:(f,l)=>l.on({click:()=>selectRegion(regionName(f),l),mouseover:e=>e.target.setStyle({fillColor:'#17131d',color:'#7657ff'}),mouseout:e=>{if(e.target!==selectedLayer)e.target.setStyle(regionStyle())}})}).addTo(map)}
function renderEvents(){const profile=JSON.parse(localStorage.getItem('sonaProfile')||'null');const near=profile?.city?Object.entries({Firenze:'Toscana',Milano:'Lombardia',Roma:'Lazio',Napoli:'Campania',Palermo:'Sicilia'}).find(([c])=>norm(c)===norm(profile.city))?.[1]||'Toscana':'Toscana';const mode=$('.event-filter.active')?.dataset.region||near,q=norm($('#eventSearch').value);const list=EVENTS.filter(e=>(mode==='Italia'||e.region===mode)&&(!q||norm(`${e.title} ${e.city} ${e.region}`).includes(q)));$('#eventsLocation').textContent=mode==='Italia'?'Italia':mode;const ids=JSON.parse(localStorage.getItem('sonaRsvp')||'[]');$('#eventsList').innerHTML=list.length?list.map(e=>`<article class="event-card"><div class="event-date">${e.date} · ${e.city.toUpperCase()}</div><h3>${e.title}</h3><p>${e.desc}</p><div class="event-foot"><small>${e.region}</small><button class="rsvp ${ids.includes(e.id)?'done':''}" data-rsvp="${e.id}">${ids.includes(e.id)?'PARTECIPERAI':'CONFERMA PARTECIPAZIONE'}</button></div></article>`).join(''):'<div class="profile"><b>Nessun evento trovato.</b><small>Prova Tutta Italia.</small></div>';$$('[data-rsvp]').forEach(b=>b.onclick=()=>{let a=JSON.parse(localStorage.getItem('sonaRsvp')||'[]'),id=+b.dataset.rsvp;a=a.includes(id)?a.filter(x=>x!==id):[...a,id];localStorage.setItem('sonaRsvp',JSON.stringify(a));renderEvents()})}
function renderEventPreview(){const list=EVENTS.slice(0,3);$('#eventsPreviewList').innerHTML=list.map(e=>`<article class="event-card"><div class="date">${e.date} · ${e.city}</div><h3>${e.title}</h3><p>${e.desc}</p><button data-preview="${e.id}">PARTECIPA</button></article>`).join('');$$('[data-preview]').forEach(b=>b.onclick=()=>{$('#eventsPanel').classList.add('open');renderEvents()})}
function openSheet(){const p=JSON.parse(localStorage.getItem('sonaProfile')||'null');if(p){$('#ig').value=p.ig||'';$('#city').value=p.city||'';$$('[data-profile]').forEach(b=>b.classList.toggle('selected',(p.categories||[]).concat(p.genres||[]).includes(b.dataset.value)))}$('#sheet').classList.remove('hidden')}
function saveProfile(){const cats=$$('[data-profile="cat"].selected').map(b=>b.dataset.value).slice(0,3),genres=$$('[data-profile="genre"].selected').map(b=>b.dataset.value).slice(0,3);localStorage.setItem('sonaProfile',JSON.stringify({ig:$('#ig').value.trim(),city:$('#city').value.trim(),categories:cats,genres}));$('#sheet').classList.add('hidden');renderEvents()}
function setup(){chips();buildRegions();renderProfiles();renderEventPreview();$('#search').addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(handleSearch,280)});$('#reset').onclick=resetMap;$('#citiesBack').onclick=resetMap;$('#citySearch').oninput=()=>selectedRegion&&showCities(cityCache[selectedRegion]);$('#joinOpen').onclick=openSheet;$('#closeSheet').onclick=()=>$('#sheet').classList.add('hidden');$('#save').onclick=saveProfile;$('#connectInstagram').onclick=()=>$('#connectNote').textContent='Il collegamento reale verrà attivato con OAuth ufficiale Instagram/Meta.';$('#eventsOpen').onclick=()=>{$('#eventsPanel').classList.add('open');renderEvents()};$('#eventsClose').onclick=()=>$('#eventsPanel').classList.remove('open');$$('.event-filter').forEach(b=>b.onclick=()=>{$$('.event-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderEvents()});$('#eventSearch').oninput=renderEvents;$('#locate').onclick=()=>navigator.geolocation?.getCurrentPosition(pos=>map?.flyTo([pos.coords.latitude,pos.coords.longitude],10,{duration:.7}));let sx=0,sy=0;document.addEventListener('touchstart',e=>{sx=e.changedTouches[0].clientX;sy=e.changedTouches[0].clientY},{passive:true});document.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx,dy=e.changedTouches[0].clientY-sy;if(dx>90&&Math.abs(dx)>Math.abs(dy)*1.2){$('#eventsPanel').classList.add('open');renderEvents()}},{passive:true})}
setup();const start=()=>initMap().catch(()=>$('#mapStatus').textContent='Mappa non disponibile');if('requestIdleCallback'in window)requestIdleCallback(start,{timeout:600});else setTimeout(start,120);